default:
  tags:
    - placeholder_ftp

before_script:
  - echo "Hello, $GITLAB_USER_LOGIN!"
  - echo "CI_REGISTRY_IMAGE:$CI_REGISTRY_IMAGE"
  - echo "CI_COMMIT_SHORT_SHA:$CI_COMMIT_SHORT_SHA"

build-job:
  stage: build
  #tags:
  #  - placeholder_ftp
  script:
    - echo "Building Dockerfile..."
    #    - docker pull $CI_REGISTRY_IMAGE:latest || true
    #    - docker build -t gitlab.cloud.gcm:5050/a.belyakov/placeholder_ftp:production_version_0.6.2 .
    #- docker pull $CI_REGISTRY_IMAGE:latest || true
    #- docker build --cache-from $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE:latest .
    #- docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
   - $CI_REGISTRY_IMAGE
     --dockerfile "${CI_REGISTRY_IMAGE}/Dockerfile"
    - docker build -t $CI_REGISTRY_IMAGE:production_version_0.6.3 .
    - docker push $CI_REGISTRY_IMAGE:latest
    - echo "Building complete."

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
