test-job:
  script:
    - echo "This is my first job!"
    - date

build-job:
  stage: build
  tags:
    - dev_test
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - echo "Building Dockerfile..."
    #    - docker pull $CI_REGISTRY_IMAGE:latest || true
    #    - docker build -t gitlab.cloud.gcm:5050/a.belyakov/placeholder_ftp:production_version_0.6.2 .
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
    - echo "Building complete."

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
