COMMONINFO:
  file_name: "config_test"
  name_regional_object: "testrcm"
NATS:
  prefix: "test"
  host: "nats.cloud.gcm"
  port: 4222
  cacheTtl: 3600
  subscriptions:
    listener_command: "phftp.commands.test"
LOCALFTP:
  host: "127.0.0.1"
  port: 21
  username: "userlocalftp.test"
MAINFTP:
  host: "127.0.0.1"
  port: 21
  username: "usermainftp.test"
