COMMONINFO:
  file_name: "config_test"
  name_regional_object: "testrcm"
  main_ftp_path_result_directory: "share_file_txt/test"
NATS:
  prefix: "test"
  host: "nats.cloud.gcm"
  port: 4222
  cache_ttl: 3600
  subscriptions:
    listener_command: "phftp.commands.test"
LOCALFTP:
  host: "127.0.0.1"
  port: 21
  username: "userlocalftp.test"
MAINFTP:
  host: "127.0.0.1"
  port: 21
  username: "someuser"
DATABASEWRITELOG:
  host: "datahook.cloud.gcm"
  port: 9200
  name_db: "name_database"
  storage_name_db: "placeholder_ftp_package"
  user: "log_writer"
