COMMONINFO:
  file_name: "config_dev"
  name_regional_object: "rcmsmk"
NATS:
  prefix: "test"
  host: "nats.cloud.gcm"
  port: 4222
  cacheTtl: 3600
  subscriptions:
    listener_command: "phftp.commands"
LOCALFTP:
  host: "127.0.0.1"
  port: 21
  username: "someuser"
MAINFTP:
  host: "127.0.0.1"
  port: 21
  username: "someuser"
DATABASEWRITELOG:
  host: "datahook.cloud.gcm"
  port: 9200
  namedb: ""
  storageNamedb: "placeholder_ftp_package"
  user: "log_writer"
