COMMONINFO:
  file_name: "config_dev"
  name_regional_object: "rcmmsk"
  main_ftp_path_result_directory: "folder_two"
  max_writing_file_limit: 45
NATS:
  prefix: "test"
  host: "nats.cloud.gcm"
  port: 4222
  cache_ttl: 3600
  subscriptions:
    listener_command: "phftp.commands.test"
LOCALFTP:
  host: "127.0.0.1"
  port: 21
  username: "someuser"
MAINFTP:
  host: "127.0.0.1"
  port: 21
  username: "someuser"
DATABASEWRITELOG:
  host: "datahook.cloud.gcm"
  port: 9200
  user: "log_writer"
  name_db: ""
  storage_name_db: "placeholder_ftp_package"
