COMMONINFO:
  file_name: "config_prod"
  name_regional_object: "gcm"
NATS:
  prefix: "test"
  host: "nats.cloud.gcm"
  port: 4222
  cacheTtl: 3600
  subscriptions:
    listener_command: "phftp.commands.test"
LOCALFTP:
  host: "ftp-users.cloud.gcm"
  port: 21
  username: "ftp-user"
MAINFTP:
  host: "ftp-users.cloud.gcm"
  port: 21
  username: "ftp-user"
DATABASEWRITELOG:
  host: "datahook.cloud.gcm"
  port: 9200
  namedb: ""
  storageNamedb: "placeholder_ftp_package"
  user: "log_writer"
